# Generated by Django 5.0.2 on 2024-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_email_alter_employee_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['email', 'university'], name='email_by_university_index'),
        ),
    ]
